# -*- coding: utf-8 -*-
"""Perpetrator Sex.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/16DqD-rVjRW_GaaeI1NQLqomsdFtsz_nH
"""

import xgboost as xgb
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.preprocessing import LabelEncoder

homicide_data = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/database.csv', low_memory=False)
homicide_data.head()

#check whether the dataset has any missing values
print('Homicide Data')
missing_values=homicide_data.isnull().sum()
missing_values

#Dropping Unrelavant columns for the preditions
homicide_data_new=homicide_data.drop(
    ['Record ID', 'Agency Code', 'Agency Name', 'Agency Type', 'Victim Ethnicity','Perpetrator Ethnicity','City','State', 'Year', 'Month','Incident','Record Source','Crime Type','Perpetrator Age','Perpetrator Race'],
    axis=1,
    errors='ignore'
    )
homicide_data_new.head()

homicide_data_new = homicide_data_new[~homicide_data_new.isin(['Unknown']).any(axis=1)]
homicide_data_new.head()

# Convert 'Victim Age' to numeric
homicide_data_new['Victim Age'] = pd.to_numeric(homicide_data_new['Victim Age'], errors='coerce')
homicide_data_new = homicide_data_new[homicide_data_new["Victim Age"] > 0]
homicide_data_new.head()

# Check for missing values in 'Victim Age' columns before binning
print("Missing values in 'Victim Age' column:", homicide_data_new['Victim Age'].isna().sum())

# Remove rows where 'Victim Age' is missing
homicide_data_new = homicide_data_new.dropna(subset=['Victim Age'])

# Check for negative values or values greater than 100 in 'Victim Age' columns
print("Negative values in 'Victim Age':", (homicide_data_new['Victim Age'] < 0).sum())
print("Values greater than 100 in 'Victim Age':", (homicide_data_new['Victim Age'] > 100).sum())

homicide_data_new = homicide_data_new[(homicide_data_new['Victim Age'] >= 0) & (homicide_data_new['Victim Age'] <= 100)]

# Define the age bins and corresponding numeric labels
bins = [0, 18, 35, 50, 65, 100]
labels = [1, 2, 3, 4, 5]

# Categorize the 'Victim Age' into age ranges using the same bins and labels
homicide_data_new['Victim Age Group'] = pd.cut(homicide_data_new['Victim Age'], bins=bins, labels=labels, right=False)
homicide_data_new = homicide_data_new.drop(columns=['Victim Age'])

# Check for missing values after binning
print("Missing values in 'Victim Age Group' column:", homicide_data_new['Victim Age Group'].isna().sum())

# Show the first few rows of the cleaned dataset
homicide_data_new.head()

homicide_data_new.isna().sum()

# Label Encoding for "Perpetrator Race" and "Victim Race"
encoder_race = LabelEncoder()
homicide_data_new['Victim Race'] = encoder_race.fit_transform(homicide_data_new['Victim Race'])

# Label Encoding for Binary Columns
binary_cols = ['Crime Solved', 'Victim Sex']
for col in binary_cols:
    homicide_data_new[col] = LabelEncoder().fit_transform(homicide_data_new[col])

# One-Hot Encoding for Multiclass Categorical Columns
multi_cols = ['Relationship', 'Weapon']
homicide_data_new = pd.get_dummies(homicide_data_new, columns=multi_cols, drop_first=True)

homicide_data_new.head()

from sklearn.feature_selection import mutual_info_classif

# Define features and target
X = homicide_data_new.drop(columns=['Perpetrator Sex'])  # Features
y = homicide_data_new['Perpetrator Sex']  # Target

# Compute Mutual Information
mi_scores = mutual_info_classif(X, y)
mi_scores_df = pd.DataFrame({'Feature': X.columns, 'MI Score': mi_scores})
mi_scores_df = mi_scores_df.sort_values(by='MI Score', ascending=False)

# Display top 10 features
mi_scores_df.head(20)

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, classification_report
from imblearn.over_sampling import SMOTE


# Select top features based on MI Scores
#selected_features = ['Victim Sex', 'Relationship_Husband','Crime Solved', 'Weapon_Handgun','Relationship_Boyfriend','Victim Race','Relationship_Stranger']
selected_features = ['Victim Sex', 'Weapon_Handgun','Victim Age Group', 'Weapon_Knife','Victim Race','Weapon_Rifle','Victim Count']


# X (features) and y (target)
X = homicide_data_new[selected_features]
y = homicide_data_new['Perpetrator Sex']
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42, stratify=y)

# Normalize numerical feature
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

# Apply SMOTE to handle class imbalance in training data
smote = SMOTE(random_state=42)
X_train_resampled, y_train_resampled = smote.fit_resample(X_train_scaled, y_train)

#Logistic Regression Model
model = LogisticRegression()
model.fit(X_train_scaled, y_train)
y_pred = model.predict(X_test_scaled)

accuracy = accuracy_score(y_test, y_pred)
print(f"Model Accuracy: {accuracy:.4f}")
print("\nClassification Report:\n", classification_report(y_test, y_pred, zero_division=1))

from sklearn.metrics import confusion_matrix
import seaborn as sns
import matplotlib.pyplot as plt

conf_matrix = confusion_matrix(y_test, y_pred)
plt.figure(figsize=(6, 5))
sns.heatmap(conf_matrix, annot=True, fmt='d', cmap='Blues', xticklabels=['Male', 'Female'], yticklabels=['Male', 'Female'])
plt.xlabel('Predicted')
plt.ylabel('Actual')
plt.title('Confusion Matrix')
plt.show()

results = pd.DataFrame({
    'Actual': y_test.head(50).reset_index(drop=True),
    'Predicted': y_pred[:50]
})

print("\nFirst 50 Predictions vs Actual Results:")
results

import pickle

# Save the scaler to a .pkl file
with open('SexScaler.pkl', 'wb') as f:
    pickle.dump(scaler, f)
print("Scaler saved to SexScaler.pkl")


# Save the model to a .pkl file
with open('SexModel.pkl', 'wb') as f:
    pickle.dump(model, f)
print("Model saved to SexModel.pkl")

from google.colab import files

# Download the scaler file
files.download('SexScaler.pkl')

# Download the model file
files.download('SexModel.pkl')

!ls