# -*- coding: utf-8 -*-
"""Perpetrator  Race.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/18Bi668MpkCcS5jIgfMPHWVUNWVua4MQa
"""

import xgboost as xgb
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.preprocessing import LabelEncoder, OneHotEncoder

homicide_data = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/database.csv', low_memory=False)
homicide_data.head()

#check whether the dataset has any missing values
print('Homicide Data')
missing_values=homicide_data.isnull().sum()
missing_values

#Dropping Unrelavant columns for the preditions
homicide_data_new=homicide_data.drop(
    ['Record ID', 'Agency Code', 'Agency Name', 'Agency Type', 'Victim Ethnicity','Perpetrator Ethnicity','City','State', 'Year', 'Month','Incident','Record Source','Crime Type','Perpetrator Sex','Perpetrator Age'],
    axis=1,
    errors='ignore'
    )
homicide_data_new.head()

homicide_data_new = homicide_data_new[~homicide_data_new.isin(['Unknown']).any(axis=1)]
homicide_data_new.head()

# Convert 'Victim Age' to numeric
homicide_data_new['Victim Age'] = pd.to_numeric(homicide_data_new['Victim Age'], errors='coerce')
homicide_data_new = homicide_data_new[homicide_data_new["Victim Age"] > 0]
homicide_data_new.head()

# Check for missing values in 'Victim Age' columns before binning and removing missing values
homicide_data_new['Victim Age'].isna().sum()
homicide_data_new = homicide_data_new.dropna(subset=['Victim Age'])

# Check for negative values or values greater than 100 in 'Perpetrator Age' and 'Victim Age' columns
print("Negative values in 'Victim Age':", (homicide_data_new['Victim Age'] < 0).sum())
print("Values greater than 100 in 'Victim Age':", (homicide_data_new['Victim Age'] > 100).sum())
homicide_data_new = homicide_data_new[(homicide_data_new['Victim Age'] >= 0) & (homicide_data_new['Victim Age'] <= 100)]

# Define the age bins
bins = [0, 18, 35, 50, 65, 100]
labels = [1, 2, 3, 4, 5]

# Categorize the 'Victim Age' into age ranges using the same bins and labels
homicide_data_new['Victim Age Group'] = pd.cut(homicide_data_new['Victim Age'], bins=bins, labels=labels, right=False)
homicide_data_new = homicide_data_new.drop(columns=['Victim Age'])

# Check for missing values after binning
print("Missing values in 'Victim Age Group' column:", homicide_data_new['Victim Age Group'].isna().sum())
homicide_data_new.head()

# Check for 'Unknown' values across all columns in the dataset
unknown_values = homicide_data_new[homicide_data_new.isin(['Unknown']).any(axis=1)]

# Display the rows with 'Unknown' values
if not unknown_values.empty:
    print("Rows with 'Unknown' values in the dataset:")
    print(unknown_values)
else:
    print("No 'Unknown' values in the dataset.")

# Label Encoding for "Perpetrator Race" and "Victim Race"
encoder_race = LabelEncoder()
homicide_data_new['Perpetrator Race'] = encoder_race.fit_transform(homicide_data_new['Perpetrator Race'])
homicide_data_new['Victim Race'] = encoder_race.fit_transform(homicide_data_new['Victim Race'])

# Label Encoding for Binary Columns
binary_cols = ['Crime Solved', 'Victim Sex']
for col in binary_cols:
    homicide_data_new[col] = LabelEncoder().fit_transform(homicide_data_new[col])

# One-Hot Encoding for Multiclass Categorical Columns
multi_cols = ['Relationship', 'Weapon']
homicide_data_new = pd.get_dummies(homicide_data_new, columns=multi_cols, drop_first=True)

homicide_data_new.head()

homicide_data_new.isna().sum()

from sklearn.feature_selection import mutual_info_classif

# Define features and target
X = homicide_data_new.drop(columns=['Perpetrator Race'])  # Features
y = homicide_data_new['Perpetrator Race']  # Target

# Compute Mutual Information
mi_scores = mutual_info_classif(X, y, discrete_features=True)
mi_scores_df = pd.DataFrame({'Feature': X.columns, 'MI Score': mi_scores})
mi_scores_df = mi_scores_df.sort_values(by='MI Score', ascending=False)

# Display top 10 features
mi_scores_df.head(20)

from imblearn.over_sampling import SMOTE
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from xgboost import XGBClassifier
from sklearn.metrics import accuracy_score, classification_report

# Select the best features based on MI scores
selected_features = ['Victim Race','Victim Age Group','Weapon_Handgun','Victim Sex','Victim Count','Weapon_Rifle','Weapon_Shotgun']

#X (features) and y (target)
X = homicide_data_new[selected_features]
y = homicide_data_new['Perpetrator Race']
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42, stratify=y)

# Applying SMOTE to balance classes
smote = SMOTE(random_state=42)
X_train_resampled, y_train_resampled = smote.fit_resample(X_train, y_train)

# Normalize numerical features
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train_resampled)
X_test_scaled = scaler.transform(X_test)

# Train XGBoost Classifier with tuned hyperparameters
model = XGBClassifier(
    objective='multi:softmax',
    num_class=len(y.unique()),
    eval_metric='mlogloss',
    learning_rate=0.1,
    n_estimators=200,
    max_depth=6,
    subsample=0.8,
    colsample_bytree=0.8,
    random_state=42
)

model.fit(X_train_scaled, y_train_resampled)
y_pred = model.predict(X_test_scaled)

#Performance
accuracy = accuracy_score(y_test, y_pred)
print(f"Model Accuracy: {accuracy:.4f}")
print("\nClassification Report:\n", classification_report(y_test, y_pred))

from sklearn.metrics import confusion_matrix
import seaborn as sns
import matplotlib.pyplot as plt

conf_matrix = confusion_matrix(y_test, y_pred)
plt.figure(figsize=(8, 6))
sns.heatmap(conf_matrix, annot=True, fmt='d', cmap='Blues', xticklabels=y.unique(), yticklabels=y.unique())
plt.xlabel('Predicted')
plt.ylabel('Actual')
plt.title('Confusion Matrix for XGBoost Classifier')
plt.show()

# Mapping of encoded values to race labels
race_mapping = {
    2: "Native American/Alaska Native",
    3: "White",
    1: "Black",
    0: "Asian/Pacific Islander"
}

# Convert predicted values to original race labels
predictions_original = [race_mapping.get(pred, "Unknown") for pred in y_pred]

# Convert actual values to original race labels
actual_values_original = [race_mapping.get(val, "Unknown") for val in y_test]

# Display the results
for i in range(50):
    print(f"Prediction: {predictions_original[i]}, Actual: {actual_values_original[i]}")

import pickle

# Save the scaler
with open('RaceScaler.pkl', 'wb') as f:
    pickle.dump(scaler, f)
print("Race Scaler saved to RaceScaler.pkl")

# Save the model
with open('RaceModel.pkl', 'wb') as f:
    pickle.dump(model, f)
print("Race Model saved to RaceModel.pkl")

from google.colab import files

# Download the scaler file
files.download('RaceScaler.pkl')

# Download the model file
files.download('RaceModel.pkl')

